ratings:
  paths:
    - build/**
    - docs/**
    - src/**
    - test/**

exclude_paths:
  - coverage/*
  - dist/*

engines:
  eslint:
    enabled: true

  duplication:
    enabled: true
    exclude_paths:
      - "*.test.js"

  fixme:
    enabled: true
    exclude_paths:
      - ".github/"
