ratings:
  paths:
    - build/**
    - docs/**
    - src/**
    - test/**

exclude_paths:
  - coverage/*
  - dist/*

engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 90
        vue:
          mass_threshold: 90
  fixme:
    enabled: true
    exclude_paths:
      - "build/"
      - "docs/"
