ratings:
  paths:
    - build/**
    - docs/**
    - src/**
    - test/**

exclude_paths:
  - coverage/*
  - dist/*

engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70
  fixme:
    enabled: true
    exclude_paths:
      - ".github/"
