ratings:
  paths:
    - build/**
    - docs/**
    - src/**
    - test/**

exclude_paths:
  - coverage/*
  - dist/*

engines:
  eslint:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
        javascript:
          patterns:
            - "src/**/*.js"
            - "src/**/*.vue"
            - "build/**/*.js"
            - "build/**/*.vue"
            - "test/**/*.js"
            - "test/**/*.vue"
            - "!src/**/*.test.js"

  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
      MD013:
        enabled: false
      MD038:
        enabled: false
      MD026:
        enabled: false
      MD033:
        enabled: false
      MD014:
        enabled: false

  fixme:
    enabled: true
    exclude_paths:
      - ".github/"
